### ISSUE TITLE
Fan header and RGB lights

### ISSUE THREAD

**Issue by t3hk0d3** [NabuCasa/yellow#61]
Is there any reason why they are not mentioned anywhere in documentation?

**Comment by agners** [comment]
They aren't soldered on, so we didn't deem to document those. Especially the controller for the RGB lights wouldn't be easy to populate for most people. And folks who can do it are probably fine looking at the schematics/layout directly :smile:

**Comment by t3hk0d3** [comment]
@agners Just out of curiosity - what is a point having these on PCB, but never soldering them? Base for future versions/modifications?

**Comment by agners** [comment]
> @agners Just out of curiosity - what is a point having these on PCB, but never soldering them? Base for future versions/modifications?

Essentially component shortage fallout. It was late to implement PCB modifications so we just went for assembly options. We did consider adding it later, but it seems a bit late at this point, since people are used to and documentation has been written etc. etc..

**Comment by agners** [comment]
> I am still trying to figure out how to make them work with device tree :D

Yeah that was the other problem: I think it requires kernel source modifications as well :sweat_smile: 

Here you can find some nuggets to get that going :smile: 
<https://github.com/NabuCasa/raspberrypi-linux/commits/rpi-5.10.y-ha-led-lp5569-forums>

**Comment by t3hk0d3** [comment]
> > @agners Just out of curiosity - what is a point having these on PCB, but never soldering them? Base for future versions/modifications?
> 
> Essentially component shortage fallout. It was late to implement PCB modifications so we just went for assembly options. We did consider adding it later, but it seems a bit late at this point, since people are used to and documentation has been written etc. etc..

Any chance for `Home Assistant Yellow Max` version? 😉
