### ISSUE TITLE
Google Coral USB Stick

### ISSUE THREAD

**Issue by arne182** [NabuCasa/yellow#63]
Is there a way to get a USB 3.0 interface so that I can use the full potential of the Google Coral Stick?

**Comment by agners** [comment]
The Raspberry Pi Compute Module 4 has no native USB 3.0 support. The way USB 3.0 is implemented on Raspberry Pi and other boards is through a PCIe to USB 3.0 bridge.

On Yellow the PCIe lines are routed to the M.2 connector. Technically, you can use a M.2 PCIe to USB 3.0 adapter, but they don't seem all that common in practice. 

Anther way would be to build a M.2 module with a PCIe to USB 3.0 bridge and a Coral on-board. It seems that there are designs out there for such a device, see https://github.com/will127534/Coral-USB3-M2-Module.

But from a Yellow perspective, there is no plans to build a variant which comes with a PCIe to USB 3.0 bridge on-board.
